"""add confidence review columns and code_embedding table

Revision ID: 442b23c29265
Revises: 6387eefc110d
Create Date: 2026-02-27 19:06:09.779584

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = "442b23c29265"
down_revision: Union[str, Sequence[str], None] = "6387eefc110d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_embedding",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("code_system", sa.String(length=10), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(1024), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_code_embedding_hnsw",
        "code_embedding",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index("idx_code_system", "code_embedding", ["code_system"], unique=False)
    op.create_index(
        "uq_code_system_code", "code_embedding", ["code_system", "code"], unique=True
    )
    op.add_column("disease", sa.Column("confidence", sa.Float(), nullable=True))
    op.add_column(
        "disease",
        sa.Column(
            "review_status",
            sa.String(length=30),
            server_default="pending_review",
            nullable=False,
        ),
    )
    op.add_column("disease", sa.Column("review_notes", sa.Text(), nullable=True))
    op.add_column("disease", sa.Column("candidates_json", sa.Text(), nullable=True))
    op.add_column("medication", sa.Column("confidence", sa.Float(), nullable=True))
    op.add_column(
        "medication",
        sa.Column(
            "review_status",
            sa.String(length=30),
            server_default="pending_review",
            nullable=False,
        ),
    )
    op.add_column("medication", sa.Column("review_notes", sa.Text(), nullable=True))
    op.add_column("procedure", sa.Column("confidence", sa.Float(), nullable=True))
    op.add_column(
        "procedure",
        sa.Column(
            "review_status",
            sa.String(length=30),
            server_default="pending_review",
            nullable=False,
        ),
    )
    op.add_column("procedure", sa.Column("review_notes", sa.Text(), nullable=True))
    op.add_column("procedure", sa.Column("candidates_json", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("procedure", "candidates_json")
    op.drop_column("procedure", "review_notes")
    op.drop_column("procedure", "review_status")
    op.drop_column("procedure", "confidence")
    op.drop_column("medication", "review_notes")
    op.drop_column("medication", "review_status")
    op.drop_column("medication", "confidence")
    op.drop_column("disease", "candidates_json")
    op.drop_column("disease", "review_notes")
    op.drop_column("disease", "review_status")
    op.drop_column("disease", "confidence")
    op.drop_index("uq_code_system_code", table_name="code_embedding")
    op.drop_index("idx_code_system", table_name="code_embedding")
    op.drop_index(
        "idx_code_embedding_hnsw",
        table_name="code_embedding",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("code_embedding")
    # ### end Alembic commands ###
