"""add_is_drug_class_to_medication

Revision ID: 4ceaf3bd7ecf
Revises: 442b23c29265
Create Date: 2026-03-02 11:47:56.908859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ceaf3bd7ecf'
down_revision: Union[str, Sequence[str], None] = '442b23c29265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('is_drug_class', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication', 'is_drug_class')
    # ### end Alembic commands ###
