"""add disease procedure tables and medication cui column

Revision ID: 6387eefc110d
Revises: d1f2c8a7b9e1
Create Date: 2026-02-26 20:42:21.826777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6387eefc110d'
down_revision: Union[str, Sequence[str], None] = 'd1f2c8a7b9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cui', sa.String(), nullable=True),
    sa.Column('icd10_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cui'),
    sa.UniqueConstraint('name')
    )
    op.create_table('procedure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cui', sa.String(), nullable=True),
    sa.Column('cpt_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cui'),
    sa.UniqueConstraint('name')
    )
    op.create_table('report_disease',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('onset_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_procedure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('date_performed', sa.DateTime(), nullable=True),
    sa.Column('body_site', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('medication', sa.Column('cui', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'medication', ['cui'])
    op.drop_index(op.f('ix_report_content_hash'), table_name='report')
    op.drop_index(op.f('ix_report_extracted_text_hash'), table_name='report')
    op.create_unique_constraint(None, 'report', ['content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='unique')
    op.create_index(op.f('ix_report_extracted_text_hash'), 'report', ['extracted_text_hash'], unique=False)
    op.create_index(op.f('ix_report_content_hash'), 'report', ['content_hash'], unique=True)
    op.drop_constraint(None, 'medication', type_='unique')
    op.drop_column('medication', 'cui')
    op.drop_table('report_procedure')
    op.drop_table('report_disease')
    op.drop_table('procedure')
    op.drop_table('disease')
    # ### end Alembic commands ###
