"""add_review_cols_to_join_tables

Revision ID: 94e89ecc4829
Revises: 4ceaf3bd7ecf
Create Date: 2026-03-02 13:18:51.805713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e89ecc4829'
down_revision: Union[str, Sequence[str], None] = '4ceaf3bd7ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_disease', sa.Column('coding_confidence', sa.Float(), nullable=True))
    op.add_column('report_disease', sa.Column('review_status', sa.String(length=30), server_default='pending_review', nullable=False))
    op.add_column('report_disease', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('report_disease', sa.Column('candidates_json', sa.Text(), nullable=True))
    op.add_column('report_medication', sa.Column('coding_confidence', sa.Float(), nullable=True))
    op.add_column('report_medication', sa.Column('review_status', sa.String(length=30), server_default='pending_review', nullable=False))
    op.add_column('report_medication', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('report_medication', sa.Column('candidates_json', sa.Text(), nullable=True))
    op.add_column('report_procedure', sa.Column('coding_confidence', sa.Float(), nullable=True))
    op.add_column('report_procedure', sa.Column('review_status', sa.String(length=30), server_default='pending_review', nullable=False))
    op.add_column('report_procedure', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('report_procedure', sa.Column('candidates_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_procedure', 'candidates_json')
    op.drop_column('report_procedure', 'review_notes')
    op.drop_column('report_procedure', 'review_status')
    op.drop_column('report_procedure', 'coding_confidence')
    op.drop_column('report_medication', 'candidates_json')
    op.drop_column('report_medication', 'review_notes')
    op.drop_column('report_medication', 'review_status')
    op.drop_column('report_medication', 'coding_confidence')
    op.drop_column('report_disease', 'candidates_json')
    op.drop_column('report_disease', 'review_notes')
    op.drop_column('report_disease', 'review_status')
    op.drop_column('report_disease', 'coding_confidence')
    # ### end Alembic commands ###
